version: "3"
services: 

    db:
        image: postgres
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        ports:
            - "5432:5432"

    back:
        build:
            context: ./
        volumes: 
            - .:/code
        ports: 
            - "8000:8000"
        command: python manage.py runserver 0.0.0.0:8000
        depends_on: 
            - db

    front:
        build:
            context: ./frontend
        command: "npm run serve"
        volumes:
            - ./:/app/
            - ./frontend/node_modules:/app/frontend/node_modules
        ports:
            - "8080:8080"